// 3rd-party/mermaid-live-editor/src/routes/auth/signup/+page.svelte
<script lang="ts">
  import { Button } from '$/components/ui/button';
  import { Input } from '$/components/ui/input';
  import { authClient } from '$lib/auth-client';
  import { page } from '$app/stores';

  let inviteToken = $state($page.url.searchParams.get('token') ?? '');
  let email = $state('');
  let password = $state('');
  let name = $state('');
  let errorMsg = $state('');
  let loading = $state(false);

  async function handleSignup() {
    errorMsg = '';

    if (!inviteToken.trim()) {
      errorMsg = 'An invite token is required to sign up.';
      return;
    }
    if (!email.trim() || !password.trim()) {
      errorMsg = 'Email and password are required.';
      return;
    }
    if (password.length < 8) {
      errorMsg = 'Password must be at least 8 characters.';
      return;
    }

    loading = true;
    try {
      const res = await fetch('/api/auth/signup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email,
          password,
          name: name || undefined,
          inviteToken: inviteToken.trim()
        })
      });

      if (!res.ok) {
        const data = await res.json().catch(() => null);
        errorMsg = data?.message || `Signup failed (${res.status})`;
        loading = false;
        return;
      }

      await authClient.signIn.email({ email, password, callbackURL: '/edit' });
    } catch (e: unknown) {
      errorMsg = e instanceof Error ? e.message : 'An unexpected error occurred.';
      loading = false;
    }
  }
</script>

<div class="rounded-lg border border-border bg-card p-6 shadow-sm">
  <div class="space-y-4">
    <div>
      <label for="invite-token" class="mb-1 block text-sm font-medium text-foreground">
        Invite Token
      </label>
      <Input
        id="invite-token"
        type="text"
        placeholder="Enter your invite token"
        bind:value={inviteToken}
        autocomplete="off" />
    </div>

    <div>
      <label for="name" class="mb-1 block text-sm font-medium text-foreground">
        Name <span class="text-muted-foreground">(optional)</span>
      </label>
      <Input id="name" type="text" placeholder="Your name" bind:value={name} autocomplete="name" />
    </div>

    <div>
      <label for="email" class="mb-1 block text-sm font-medium text-foreground">Email</label>
      <Input
        id="email"
        type="email"
        placeholder="you@example.com"
        bind:value={email}
        autocomplete="email" />
    </div>

    <div>
      <label for="password" class="mb-1 block text-sm font-medium text-foreground">Password</label>
      <Input
        id="password"
        type="password"
        placeholder="At least 8 characters"
        bind:value={password}
        autocomplete="new-password" />
    </div>

    {#if errorMsg}
      <p class="rounded bg-destructive/10 p-2 text-sm text-destructive">{errorMsg}</p>
    {/if}

    <Button class="w-full" size="lg" disabled={loading} onclick={handleSignup}>
      {#if loading}
        Creating account...
      {:else}
        Sign up
      {/if}
    </Button>
  </div>
</div>

<div class="space-y-2 text-center">
  <a href="/auth/login" class="text-sm text-muted-foreground hover:text-foreground">
    Already have an account? Sign in
  </a>
  <span class="mx-2 text-muted-foreground">·</span>
  <a href="/edit" class="text-sm text-muted-foreground hover:text-foreground">
    Continue without signing in
  </a>
</div>

// projects/codefre.sh/app/frontend/src/app/signup/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useAuth } from "@/context/auth";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Card, FormField, TextInput, Button, toast } from "@/components/ui";

export default function SignupPage() {
  const { register } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (process.env.NEXT_PUBLIC_DEMO_MODE === 'true') {
      router.push('/app');
    }
  }, [router]);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [inviteToken, setInviteToken] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    if (!inviteToken.trim()) {
      const msg = "Invite token is required";
      setError(msg);
      toast.error(msg);
      return;
    }

    setLoading(true);

    try {
      await register(email, password, inviteToken);
      toast.success("Account created");
      router.push("/app");
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Registration failed";
      setError(msg);
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      className="auth-card-wrap"
      data-cy="auth-card-wrap"
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "calc(100vh - 80px)",
        padding: "2rem 1rem",
      }}
    >
      <Card
        className="sg-card--auth"
        data-cy="auth-card"
        data-cy-id="signup"
        style={{ width: "100%", maxWidth: 420, padding: "2rem" }}
      >
        <h1
          className="sg-page-header__title"
          data-cy="auth-title"
          style={{ marginTop: 0, marginBottom: "1.5rem" }}
        >
          Sign Up
        </h1>

        {error && (
          <p className="sg-error" data-cy="auth-error" role="alert">
            {error}
          </p>
        )}

        <form onSubmit={handleSubmit} data-cy="auth-form" data-cy-id="signup">
          <FormField label="Invite token" name="invite_token" required>
            {(p) => (
              <TextInput
                {...p}
                type="text"
                value={inviteToken}
                onChange={(e) => setInviteToken(e.target.value)}
                autoComplete="off"
                placeholder="ct_..."
                data-cy="invite-token-input"
                error={!!error && !inviteToken.trim()}
              />
            )}
          </FormField>

          <FormField label="Email" name="email" required>
            {(p) => (
              <TextInput
                {...p}
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                autoComplete="email"
                placeholder="you@example.com"
                data-cy="auth-email-input"
                error={!!error && !!inviteToken.trim()}
              />
            )}
          </FormField>

          <FormField
            label="Password"
            name="password"
            hint="At least 8 characters"
            required
          >
            {(p) => (
              <TextInput
                {...p}
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                minLength={8}
                autoComplete="new-password"
                data-cy="auth-password-input"
                error={!!error && !!inviteToken.trim()}
              />
            )}
          </FormField>

          <Button
            type="submit"
            variant="primary"
            loading={loading}
            cy="auth-submit"
            cyValue={loading ? "loading" : "ready"}
            style={{ width: "100%", marginTop: "0.5rem" }}
          >
            {loading ? "Creating account..." : "Sign Up"}
          </Button>
        </form>

        <div style={{ marginTop: "1rem" }}>
          <p>
            Already have an account?{" "}
            <Link href="/login" data-cy="auth-login-link">
              Log in
            </Link>
          </p>
        </div>
      </Card>
    </div>
  );
}
